name: laravel-tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pcntl, pdo_mysql
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Validasi File PHP yang Di-push
        run: php artisan validate:php-files
